# Generated by Django 4.2.7 on 2026-03-10 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_track_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('artist', models.CharField(max_length=500)),
                ('album', models.CharField(blank=True, max_length=500)),
                ('album_art', models.URLField(blank=True)),
                ('energy', models.FloatField(default=0)),
                ('valence', models.FloatField(default=0)),
                ('danceability', models.FloatField(default=0)),
                ('acousticness', models.FloatField(default=0)),
                ('tempo', models.FloatField(default=0)),
                ('speechiness', models.FloatField(default=0)),
                ('instrumentalness', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'songs',
            },
        ),
        migrations.CreateModel(
            name='SpotifyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_image', models.URLField(blank=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expires', models.DateTimeField(null=True)),
                ('personality_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'spotify_users',
            },
        ),
        migrations.CreateModel(
            name='UserTopSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('time_range', models.CharField(default='medium_term', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_songs', to='api.spotifyuser')),
            ],
            options={
                'db_table': 'user_top_songs',
                'unique_together': {('user', 'song', 'time_range')},
            },
        ),
    ]
